### ISSUE TITLE
[RFE] Provide a tool to get module-build-macros SRPM out of modulemd YAML

### ISSUE THREAD

**Issue by voxik** [rpm-software-management/modulemd-tools#10]
Because the module-build-macros SRPM is the central piece for building module package, it would be useful to have a simple tool, which would provide the module-build-macros SRPM out of modulemd YAML. Having the SRPM at hand, it would allow me to build modular packages by hand in Mock.

Basically, is should be some simple command line tool, which calls the `KojiModuleBuilder.get_disttag_srpm`

May be I should contact the fedpkg developers, because calling fedpkg srpm in directory with module YAML file could be interesting variant.

Originally requested [here](https://pagure.io/fm-orchestrator/issue/1217), but I figured this might be better place.

**Comment by FrostyX** [comment]
This sounds really interesting, thank you for filing the RFE @voxik.
I am going to investigate it.
