### ISSUE TITLE
need installation instructions

### ISSUE THREAD

**Issue by Tovli** [rpm-software-management/modulemd-tools#38]
Hi
I'm trying to use this repo and not sure what should be the way to utilise it in RHEL 8
I've tried `yum install modulemd_tools` but get `Error: Unable to find a match: modulemd_tools`

Should I build it from source or is there a way to pull it like any other package?

**Comment by orenbm** [comment]
Thanks @Tovli !

I will add that it worked until a couple of weeks ago and then stopped working. Was the package removed? Is there any alternative to install this package?

**Comment by FrostyX** [comment]
Hello @Tovli,
thank you for the report and sorry for the delay. I was on PTO.

The package is actually named `modulemd-tools`, not `modulemd_tools`. So

    yum install modulemd-tools

should work.

**Comment by Tovli** [comment]
The fact is that for RHEL 8.2 it doesn't as it was removed from epel

**Comment by FrostyX** [comment]
That's correct, sorry about that. It is available only since RHEL 8.5.
I still maintain an up-to-date EPEL8 build in my Copr repository
https://copr.fedorainfracloud.org/coprs/frostyx/modulemd-tools/

Is using a Copr repo acceptable solution for you?

Also, you are right, installation instructions should definitely be in the README. I will add them.

**Comment by Tovli** [comment]
Thanks @FrostyX 
We ended up downloading the package from http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/modulemd-tools-0.7-4.el8.noarch.rpm

Copr repo might work but currently we are revisiting the need for this tool as for us it was a signal about the level of maintenance this repo has

Thanks for your reply, 
Would appreciate any comment on our chosen solution :)

**Comment by FrostyX** [comment]
@Tovli,

> Would appreciate any comment on our chosen solution :)

I think your solution is fine and simple. If it works for you, I can only be happy. The only _problem_ is that you will be stuck on 0.7-4 version. This is alright if you don't need any new tools (for instance, I released a 0.10 version with [bld2repo](https://github.com/rpm-software-management/modulemd-tools/blob/master/bld2repo/README.md)).

It is very easy to build a new version from upstream if you need. If you clone this repo and run `tito build --rpm` or `tito build --srpm` you will get the latest stable package, so you can also do this if you prefer.

> Copr repo might work but currently, we are revisiting the need for this tool as for us it was a signal about the level of maintenance this repo has

I am sorry about dropping the EPEL8 support, it wasn't meant to be a careless action in a way "whatever, I don't care, users will deal with it". On the contrary. It was solely a mistake on my side, I misunderstood some section in the RHEL documentation and unfortunately dropped the EPEL (8.4 and lower) support earlier than I was supposed to.

I do care though.

What if I created a Copr project solely for EPEL 8 builds, that would contain only stable packages, that are present in RHEL 8.5 and would be present in EPEL 8 if I hadn't dropped it.

**Comment by FrostyX** [comment]
> need installation instructions

I added the installation instructions in PR #39. What do you think @Tovli?

**Comment by Tovli** [comment]
Thanks a lot @FrostyX for taking the time and adding these clarifications.
I've added small comment to the PR. let me know what you think and I'll happily approve it afterwards

**Comment by mkulik-rh** [comment]
Seems like this issue was resolved with #39. Closing.
