### ISSUE TITLE
allow to build module without dist-git from srpms

### ISSUE THREAD

**Issue by jmlich** [rpm-software-management/modulemd-tools#50]
I am making an issue as we discussed the module build workflow with @mcurlej at devconf.

**Comment by jmlich** [comment]
Now I see, that it should be maybe in https://github.com/mcurlej/module-build

**Comment by jmlich** [comment]
sorry

**Comment by FrostyX** [comment]
No problem.
Just for the record, linking the 
issue https://github.com/mcurlej/module-build/issues/4
