### ISSUE TITLE
CI error

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/modulemd-tools#61]
```
Invalid workflow file: .github/workflows/rpm.yml#L12
The workflow is not valid. .github/workflows/rpm.yml (Line: 12, Col: 11): Input test_type is required, but not provided while calling.
```

**Comment by mkulik-rh** [comment]
This is error from old CI. You re-triggered old rpm.yml CI that wanted to trigger reusable workflow under test.yml.

My old PR branched from old master with old CI and that''s why it's failing. It's not a CI bug, new PR should be fine.

**Comment by mcurlej** [comment]
Oh ok sorry my bad
